### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by guyhajaj** [johnjones4/Standard-Notes-Clipper#28]
Just installed the Chrome version. [This page opened](chrome-extension://hhmakddlmcdddgnopbadnhmmlkmjpclb/settings/index.html). I just used the same Server URL, email and password to successfully log in to the desktop app, but here I get this error:

> Cannot read property 'length' of null

Thanks for this much-needed extension! Hoping to get it working here too.

**Comment by sequent5** [comment]
same problem with my login under chrome or chronium

**Comment by randy9999** [comment]
I have been getting the same problem.  While trying to log into Standardnotes using the notes-clipper, I keep getting a 'output is null' message. Yet I can log in to Standardnotes itself without any problems...

**Comment by johnjones4** [comment]
Hi all - I do not have a private SN server to test this against. Are you able to pull up the dev console for the extension when you try to log in? Are there any additional errors in the log or network tab?

**Comment by randy9999** [comment]
Hi,

I don't know what you mean by dev console.  The only thing I see is this...
[image: Screen Shot 2020-12-01 at 1.31.59 PM.png]
I do not see any other messages.

Also, I am logged into the standardnotes website with the same email and
password.  Without having any problems logging in.

later
Randy

**Comment by sequent5** [comment]
here it is:
settings.js:1529 TypeError: Cannot read property 'length' of null
    at SFCryptoWeb._callee128$ (chrome-extension://ocbkppilalbegahodpaibdgaodllccon/background/background.js:34284)
    at tryCatch (chrome-extension://ocbkppilalbegahodpaibdgaodllccon/background/background.js:42247)
    at Generator.invoke [as _invoke] (chrome-extension://ocbkppilalbegahodpaibdgaodllccon/background/background.js:42473)
    at Generator.prototype.<computed> [as next] (chrome-extension://ocbkppilalbegahodpaibdgaodllccon/background/background.js:42299)
    at asyncGeneratorStep (chrome-extension://ocbkppilalbegahodpaibdgaodllccon/background/background.js:23836)
    at _next (chrome-extension://ocbkppilalbegahodpaibdgaodllccon/background/background.js:23838)
doLogin$ @ settings.js:1529
tryCatch @ settings.js:604
invoke @ settings.js:830
prototype.<computed> @ settings.js:656
tryCatch @ settings.js:604
invoke @ settings.js:694
(anonymous) @ settings.js:706
Promise.then (async)
invoke @ settings.js:703
(anonymous) @ settings.js:729
callInvokeWithMethodAndArg @ settings.js:728
enqueue @ settings.js:751
prototype.<computed> @ settings.js:656
exports.async @ settings.js:775
doLogin @ settings.js:1478
login @ settings.js:1542
onClick @ settings.js:1568
N @ settings.js:84

Thanks

**Comment by randy9999** [comment]
Hi,

I just right now tried to get your Standardnotes addon to work.  It does
not work.  I still am getting the same error message...output is null.  I
have deleted and reinstalled this numerous times, with the idea that maybe
an update would start working?  Nothing yet...

later,
Randy

**Comment by JonBallinger** [comment]
I get this same issue, using server url of https://sync.standardnotes.org/ and my credentials that work for logging into standardnotes web.

**Comment by dhicosmo** [comment]
Same issue here.

**Comment by johnjones4** [comment]
Sorry for the delay here! I believe this has been resolved in https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.7.1. Can someone please confirm for me?

**Comment by JonBallinger** [comment]
Hi John,

Thanks for looking into this. Unfortunately I still get the same error.

I removed the extension, closed Chrome, then reopened Chrome, and reloaded
the extension from the new download.

Cheers,

Jonathan

**Comment by randy9999** [comment]
I too have just tried it again.  This time I downloaded a new standardnotes
from the main website.  I installed that on my mac and then downloaded and
installed this new "fix" for the extension.

But...that did not work.

I am still getting the same error 'output is null'.

later
Randy

**Comment by sequent5** [comment]
I have just tried it  with latest release 1.7.1, same error as last release 1.7.0 : Cannot read property 'length' of null.

**Comment by johnjones4** [comment]
I tested this against a version of SN server running according to these instructions: https://docs.standardnotes.org/self-hosting/docker. Can you please add more details about your server installation so I can better test?

**Comment by JonBallinger** [comment]
I'm using it against the web version. Not self hosted.

**Comment by sequent5** [comment]
I tested this against two version( a self-hosting and a official web),  same error while logging :Cannot read property 'length' of null.
so I dont't think this error is related with standardnotes itself.

**Comment by JaspalSuri** [comment]
Hi @johnjones4,

I was unable to reproduce this issue for an account that is using v003 of [SNJS](https://github.com/standardnotes/snjs/), which would be what most accounts are using/on at the moment. I was able to view my tags in the [legacy web app](app-legacy.standardnotes.org) but not in the latest [web app](app.standardnotes.org). You can create a test 003 account via the [legacy web app](app-legacy.standardnotes.org). 

However, for an account that is using v004 of SNJS, which would used by any account that was upgraded by a user changing their password via the desktop app after early November (of 2020) or by anyone who has made a new account since then, I was able to reproduce the issue and wasn't able to log in. 

I also noticed that the extension doesn't appear to add tags that contain spaces or periods. Is this intentional? Periods help nest tags underneath each other and spaces are allowed in tag names. 

Please let me know if you have any questions! Thanks for the updates so far and for maintaining this extension!

**Comment by dhicosmo** [comment]
The same issue remains for me as well. Version 1.7.1.

**Comment by JonBallinger** [comment]
This would fit with me, I created my account in November 2020 during the
cyber week sale.

**Comment by sequent5** [comment]
can log in using server url https://sync.standardnotes.org/ while letting E-mail/password empty.

**Comment by JonBallinger** [comment]
It gives the impression of logging in here as well when I use blank
email/password, but none of my clips after having done so have surfaced in
my notes anywhere.

**Comment by Rustymage** [comment]
I'm having this issue too.

Self hosted using SN instructions yesterday.

**Comment by bscott** [comment]
**Update:**

The Javascript library used in the SN Web Clipper is no longer supported by Standard Notes, That package is obsolete. The new package is SNJS. I am working on doing a refactor using the new SN JS library. We will need about a week or two to have this done then will need to test and create a new release.

**Comment by randy9999** [comment]
Thank you!  I am looking forward to maybe having a working Standard Notes.

**Comment by bscott** [comment]
A bit delayed with the updated Web Clipper but I plan on having a beta release soon.

**Comment by randy9999** [comment]
Great, thanks for the update!
